version: 2
updates:
  # main branch (Vert.x 5)
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore Vert.x 4.x and below updates on main branch
      - dependency-name: "io.vertx:*"
        versions: ["<5.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"

  # 2.x branch (Vert.x 4)
  - package-ecosystem: "maven"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"
    ignore:
      # Ignore Vert.x 5.x and above updates on 2.x branch
      - dependency-name: "io.vertx:*"
        update-types: ["version-update:semver-major"]
        versions: [">=5.0.0"]

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "2.x"
    schedule:
      interval: "weekly"