@startuml
salt
{
  {T
     +      pom.xml
     ++       src
     +++        main
     ++++         java
     +++++          org
     ++++++            acme
     +++++++            AcmeServiceDiscoveryProvider   # the provider implementation
     +++++++            AcmeServiceDiscovery               # instances used by Stork to locate a specific service
     ++++         resources
     +++++         META-INF
     ++++++         services
     +++++++         io.smallrye.stork.spi.ServiceDiscoveryProvider # just contains `org.acme.AcmeServiceDiscoveryProvider`
  }
}
@enduml