name: Post-Release
on:
  workflow_dispatch:
  push:
    branches:
      - "!*"
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'
jobs:
  post-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        name: Checkout code
        with:
          fetch-depth: 0 # fetch all commits and branches for mike to work properly
      - uses: actions/setup-java@v5
        name: Set up Java 21
        with:
          java-version: 21
          distribution: temurin
          cache: maven       
      - name: Build local artifacts
        run: mvn -B install -DskipTests  
      - name: Collect breaking changes
        run:  |
          sudo apt-get update -o Dir::Etc::sourcelist="sources.list" \
            -o Dir::Etc::sourceparts="-" -o APT::Get::List-Cleanup="0"
          sudo apt-get install -y gnupg2 gnupg-agent
          curl -s "https://get.sdkman.io" | bash
          source ~/.sdkman/bin/sdkman-init.sh && \
            sdk install jbang  
          mkdir -p target
          jbang .github/CompatibilityUtils.java extract
      - name: Update release notes
        env:
            GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        run: |
          sudo apt-get install -y gnupg2 gnupg-agent
          curl -s "https://get.sdkman.io" | bash
          source ~/.sdkman/bin/sdkman-init.sh && \
            sdk install jbang  
          export STORK_VERSION=$(cat ".github/project.yml" | yq eval '.release.current-version' -)  
          jbang .github/PublishReleaseNotes.java --release-version=$STORK_VERSION --token=$GITHUB_TOKEN